eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://localhost:1111/eureka/
server:
  port: 2222
  ssl:
        key-store: classpath:sample.jks
        key-store-password: secret
        key-password : password
