eureka:
  instance:
     leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
     preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    
server:
  port: 3333   # HTTP (Tomcat) port
